### ISSUE TITLE
Payment Processing Error

### ISSUE THREAD

**Issue by TheTechnologyStudio** [phot0n/frappe_payments#30]
Hello, I am getting this errors

`Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 408, in make_payment_request
    grand_total = get_amount(ref_doc, gateway_account.get("payment_account"))
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 518, in get_amount
    if grand_total > 0:
UnboundLocalError: local variable 'grand_total' referenced before assignment`

**Comment by TheTechnologyStudio** [comment]
any help fixing would be great

**Comment by TheTechnologyStudio** [comment]
this happens after clicking the pay button, see screen shot.

**Comment by TheTechnologyStudio** [comment]
<img width="1142" alt="Screenshot_225" src="https://user-images.githubusercontent.com/19619093/234381757-7053040c-6bc1-4dab-9a7b-53bb216f2ea0.png">

**Comment by TheTechnologyStudio** [comment]
<img width="1080" alt="Screenshot_226" src="https://user-images.githubusercontent.com/19619093/234381852-a55ee20a-8ab9-4a1c-a8c7-40627456ecc6.png">
