### ISSUE TITLE
Stripe payment on website fails

### ISSUE THREAD

**Issue by Spixmaster** [phot0n/frappe_payments#39]
I try to buy an item on the website by going to `/orders` and clicking on the button which redirects to the route `/api/method/erpnext.accounts.doctype.payment_request.payment_request.make_payment_request?dn=SAL-ORD-2023-00001&dt=Sales%20Order&submit_doc=1&order_type=Shopping%20Cart`. An error occurs.

What I find odd is that the Stripe payments worked beforehand for me.

As background information, my payment gateway is named `test1` and the set language is German. The item I am trying to buy costs 421 843 €.

I think my issue might be related to #20. As stated there, Stripe needs the payment intent way to charge over 100 € which is the case here.

I just tested it out to pay a bill less than 100 €. That did not work either and resulted in the same error message.

ERPNext version: 14.33.2
Frappe version: 14.43.1

```
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1340, in get_module
    return importlib.import_module(modulename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'frappe.core.doctype.test1_settings'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/payments/payments/utils/utils.py", line 12, in get_payment_gateway_controller
    return frappe.get_doc(f"{payment_gateway} Settings")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1197, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 72, in get_doc
    controller = get_controller(doctype)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/base_document.py", line 78, in get_controller
    return _get_controller()
           ^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/base_document.py", line 64, in _get_controller
    module = load_doctype_module(doctype, module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/modules/utils.py", line 249, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for test1 Settings, the DocType you're trying to open might be deleted.
 Error: No module named 'frappe.core.doctype.test1_settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
               ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1620, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 486, in make_payment_request
    frappe.local.response["location"] = pr.get_payment_url()
                                        ^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 201, in get_payment_url
    controller = _get_payment_gateway_controller(self.payment_gateway)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 31, in _get_payment_gateway_controller
    return get_payment_gateway_controller(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/payments/payments/utils/utils.py", line 14, in get_payment_gateway_controller
    frappe.throw(_("{0} Settings not found").format(payment_gateway))
  File "apps/frappe/frappe/__init__.py", line 534, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 502, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 451, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: test1 Einstellungen nicht gefunden
```

**Comment by Spixmaster** [comment]
I think that I found a similar issue: https://github.com/frappe/erpnext/issues/16928

**Comment by Spixmaster** [comment]
The issue was fixed when recreating the payment gateway document.
