### ISSUE TITLE
Razorpay Payment Link click showing error - There was an error building this page

### ISSUE THREAD

**Issue by scarce-infotech** [phot0n/frappe_payments#46]
We have updated API Key and Secrete in Razorpay Settings, then Updated Payment Gateway Account and Set the same as Default Payment Gateway in E-Commerce Settings also.

While Clicking the Place Order from checkout page, Order is generated Successfully with Payment Link, but when Clicking on Payment link, it's giving following error (Uncaught Server Exception - There was an error building this page)

```
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 84, in render
    html = self.get_html()
  File "apps/frappe/frappe/website/utils.py", line 517, in cache_html_decorator
    html = func(*args, **kwargs)
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 99, in get_html
    self.post_process_context()
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 109, in post_process_context
    super().post_process_context()
  File "apps/frappe/frappe/website/page_renderers/base_template_page.py", line 31, in post_process_context
    self.set_title_with_prefix()
  File "apps/frappe/frappe/website/page_renderers/base_template_page.py", line 47, in set_title_with_prefix
    and not self.context.title.startswith(self.context.title_prefix)
AttributeError: 'list' object has no attribute 'startswith'

```

any idea why it's happening?

**Comment by puspharaj-teachspot** [comment]
No wonder why this is happening! Same error with proper api key and secret!
